### PR TITLE
[ADD] Support multiple vendor prefixes on one key

### PR DESCRIPTION
**Pull request by Linard11**
While writing my manifest I noticed that certain times there were keys, not specific to one vendor, but the opposite: All support it except for e.g. Edge with _option_ui_. Having to copy this key 3 times for each vendor except Edge seemed rather inefficient and prone to errors.

So this:
```
  "__edge__options_page": "pages/options.html",
  "__chrome__options_ui": {
    "page": "pages/options.html",
    "open_in_tab": false
  },
  "__firefox__options_ui": {
    "page": "pages/options.html",
    "open_in_tab": false
  },
  "__opera__options_ui": {
    "page": "pages/options.html",
    "open_in_tab": false
  },
```
became this:
```
  "__edge__options_page": "pages/options.html",
  "__chrome|firefox|opera__options_ui": {
    "page": "pages/options.html",
    "open_in_tab": false
  },
```

**Commit message:**
Keys can contain multiple vendor prefixes seperated by either | or __
Trailing delimiters are intentionally not allowed to prevent confusion
with the __ delimiter for the whole vendor prefix.

Examples:
	Valid:
	__chrome__opera__key: value  -> key: value
	__edge|firefox__key: value   -> key: value

	Trailing |:
	__chrome|__key: value        -> __chrome|__key: value
	__chrome|opera|__key: value  -> __chrome|opera|__key: value
	__chrome__opera|__key: value -> opera|__key: value

	| after __ vendor prefix delimiter:
	__edge__|key: value          -> |key: value

	Trailing __:
	__firefox___key: value       -> _key: value
	__firefox____key: value      -> __key: value

### CODE REVIEW

**Comment by HaNdTriX** [comment]
Awesome! Thanks a lot for contributing. 

Before I merge this. Could you update the documentation as well?

**Comment by Linard11** [comment]
Will do. On second look at it, I might slightly alter the regex to allow trailing | and __ .
Also right now if you have a typo in a vendors name, the whole regex will not match. What do you think about `__chrome|**edeg**__` still working for the chrome manifest, instead of a complete missmatch? Is it maybe a good idea to have this complete failure of the key so you notice the error?

**Comment by HaNdTriX** [comment]
I like the idea to throw an error if you use an incorrect vendor key. 👍

**Comment by Linard11** [comment]
An actual error might not even be nessesary. If there is an invalid manifest key, the browser will throw an error upon installation

**Comment by HaNdTriX** [comment]
Fine with me, then 😉

**Comment by Linard11** [comment]
**Note:** first commit 85b3c7b9f2b7bdd843e9c29107a82768712748c2 changed regex behavior outline in commit message

**Comment by Linard11** [comment]
@HaNdTriX  Just a reminder, in case you forgot. It is ready for merge, unless you see anything that might need a touch-up

**Comment by HaNdTriX** [comment]
Thanks!

**Comment by Linard11** [comment]
Hey @HaNdTriX, sadly I found a bug with the splitting of the vendor keys. I already pushed the fix and I'll reopen the pull request

**Pull request merged**
